#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 09, 2024 10:51:54 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import uitemp_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1398x978+683+146")
        top.minsize(120, 1)
        top.maxsize(5124, 1710)
        top.resizable(0,  0)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(cursor="arrow")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(x=190, y=10, height=960, width=1200)
        self.Frame1.configure(relief='sunken')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="sunken")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#000000")

        self.Labelframe2 = tk.LabelFrame(self.top)
        self.Labelframe2.place(x=10, y=0, height=185, width=170)
        self.Labelframe2.configure(relief='sunken')
        self.Labelframe2.configure(font="-family {Segoe UI} -size 9")
        self.Labelframe2.configure(foreground="#000000")
        self.Labelframe2.configure(relief="sunken")
        self.Labelframe2.configure(text='''System''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(cursor="arrow")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="#000000")

        self.Label2 = tk.Label(self.Labelframe2)
        self.Label2.place(x=10, y=90, height=21, width=41, bordermode='ignore')
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 9")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''Width:''')

        self.Label1 = tk.Label(self.Labelframe2)
        self.Label1.place(x=10, y=120, height=21, width=45, bordermode='ignore')
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 9")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Height:''')

        self.Spinbox1 = tk.Spinbox(self.Labelframe2, from_=0.0, to=1000.0)
        self.Spinbox1.place(x=70, y=90, height=19, width=85, bordermode='ignore')

        self.Spinbox1.configure(activebackground="#d9d9d9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font="-family {Segoe UI} -size 9")
        self.Spinbox1.configure(foreground="#000000")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="#000000")
        self.Spinbox1.configure(insertbackground="#000000")
        self.Spinbox1.configure(selectbackground="#d9d9d9")
        self.Spinbox1.configure(selectforeground="black")
        self.Spinbox1.configure(validate="all")

        self.Spinbox2 = tk.Spinbox(self.Labelframe2, from_=0.0, to=1000.0)
        self.Spinbox2.place(x=70, y=120, height=19, width=85
                , bordermode='ignore')
        self.Spinbox2.configure(activebackground="#d9d9d9")
        self.Spinbox2.configure(background="white")
        self.Spinbox2.configure(disabledforeground="#a3a3a3")
        self.Spinbox2.configure(font="-family {Segoe UI} -size 9")
        self.Spinbox2.configure(foreground="#000000")
        self.Spinbox2.configure(highlightbackground="black")
        self.Spinbox2.configure(highlightcolor="#000000")
        self.Spinbox2.configure(insertbackground="#000000")
        self.Spinbox2.configure(selectbackground="#d9d9d9")
        self.Spinbox2.configure(selectforeground="black")
        self.Spinbox2.configure(validate="all")

        self.Label4 = tk.Label(self.Labelframe2)
        self.Label4.place(x=10, y=150, height=21, width=51, bordermode='ignore')
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 9")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="#000000")
        self.Label4.configure(text='''Cell size:''')

        self.Spinbox3 = tk.Spinbox(self.Labelframe2, from_=1.0, to=32.0)
        self.Spinbox3.place(x=70, y=150, height=19, width=85
                , bordermode='ignore')
        self.Spinbox3.configure(activebackground="#d9d9d9")
        self.Spinbox3.configure(background="white")
        self.Spinbox3.configure(disabledforeground="#a3a3a3")
        self.Spinbox3.configure(font="-family {Segoe UI} -size 9")
        self.Spinbox3.configure(foreground="#000000")
        self.Spinbox3.configure(highlightbackground="black")
        self.Spinbox3.configure(highlightcolor="#000000")
        self.Spinbox3.configure(insertbackground="#000000")
        self.Spinbox3.configure(selectbackground="#d9d9d9")
        self.Spinbox3.configure(selectforeground="black")

        self.Label3 = tk.Label(self.Labelframe2)
        self.Label3.place(x=10, y=60, height=21, width=153, bordermode='ignore')
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(cursor="arrow")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 9")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#000000")
        self.Label3.configure(text='''Dimensions (Reset to apply)''')

        self.Button5 = tk.Button(self.Labelframe2)
        self.Button5.place(x=30, y=20, height=26, width=37, bordermode='ignore')
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(cursor="hand2")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(font="-family {Segoe UI} -size 9")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="#000000")
        self.Button5.configure(text='''Load''')

        self.Button6 = tk.Button(self.Labelframe2)
        self.Button6.place(x=100, y=20, height=26, width=39, bordermode='ignore')

        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="black")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(cursor="hand2")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(font="-family {Segoe UI} -size 9")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="#000000")
        self.Button6.configure(text='''Reset''')

        self.Controls = tk.LabelFrame(self.top)
        self.Controls.place(x=10, y=190, height=85, width=170)
        self.Controls.configure(relief='sunken')
        self.Controls.configure(font="-family {Segoe UI} -size 9")
        self.Controls.configure(foreground="#000000")
        self.Controls.configure(relief="sunken")
        self.Controls.configure(text='''Simulation''')
        self.Controls.configure(background="#d9d9d9")
        self.Controls.configure(cursor="arrow")
        self.Controls.configure(highlightbackground="#d9d9d9")
        self.Controls.configure(highlightcolor="#000000")

        self.Button1 = tk.Button(self.Controls)
        self.Button1.place(x=10, y=20, height=26, width=46, bordermode='ignore')
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(cursor="hand2")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(text='''Slower''')

        self.Button4 = tk.Button(self.Controls)
        self.Button4.place(x=60, y=20, height=26, width=47, bordermode='ignore')
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(cursor="hand2")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {Segoe UI} -size 9")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="#000000")
        self.Button4.configure(text='''Stop''')

        self.Button3 = tk.Button(self.Controls)
        self.Button3.place(x=110, y=20, height=26, width=42, bordermode='ignore')

        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(cursor="hand2")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 9")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(text='''Faster''')

        self.Button2 = tk.Button(self.Controls)
        self.Button2.place(x=30, y=50, height=26, width=104, bordermode='ignore')

        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(cursor="hand2")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 9")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(state='disabled')
        self.Button2.configure(text='''Step Forward''')

        self.Controls_1 = tk.LabelFrame(self.top)
        self.Controls_1.place(x=10, y=280, height=57, width=170)
        self.Controls_1.configure(relief='sunken')
        self.Controls_1.configure(font="-family {Segoe UI} -size 9")
        self.Controls_1.configure(foreground="#000000")
        self.Controls_1.configure(relief="sunken")
        self.Controls_1.configure(text='''Layers''')
        self.Controls_1.configure(background="#d9d9d9")
        self.Controls_1.configure(cursor="fleur")
        self.Controls_1.configure(highlightbackground="#d9d9d9")
        self.Controls_1.configure(highlightcolor="#000000")

        self.Button1_1 = tk.Button(self.Controls_1)
        self.Button1_1.place(x=60, y=20, height=26, width=46
                , bordermode='ignore')
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(activeforeground="black")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(cursor="hand2")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Segoe UI} -size 9")
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="#000000")
        self.Button1_1.configure(text='''Next''')

def start_up():
    uitemp_support.main()

if __name__ == '__main__':
    uitemp_support.main()




